In [32]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\user\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('data/AmesHousing.csv');

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [5]:
data.describe(include='object')

,MS Zoning,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,...,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Pool QC,Fence,Misc Feature,Sale Type,Sale Condition
count,2930,2930,198,2930,2930,2930,2930,2930,2930,2930,...,2773,2771,2771,2771,2930,13,572,106,2930,2930
unique,7,2,2,4,4,3,5,3,28,9,...,6,3,5,5,3,4,4,5,10,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
freq,2273,2918,120,1859,2633,2927,2140,2789,443,2522,...,1731,1231,2615,2665,2652,4,330,95,2536,2413

In [6]:
a = pd.DataFrame()
a['columns'] = list(data.columns)
a['nulls'] = list(data.isna().sum())

In [7]:
pd.options.display.max_rows = 90

In [8]:
a

            columns  nulls
0             Order      0
1               PID      0
2       MS SubClass      0
3         MS Zoning      0
4      Lot Frontage    490
5          Lot Area      0
6            Street      0
7             Alley   2732
8         Lot Shape      0
9      Land Contour      0
10        Utilities      0
11       Lot Config      0
12       Land Slope      0
13     Neighborhood      0
14      Condition 1      0
15      Condition 2      0
16        Bldg Type      0
17      House Style      0
18     Overall Qual      0
19     Overall Cond      0
20       Year Built      0
21   Year Remod/Add      0
22       Roof Style      0
23        Roof Matl      0
24     Exterior 1st      0
25     Exterior 2nd      0
26     Mas Vnr Type   1775
27     Mas Vnr Area     23
28       Exter Qual      0
29       Exter Cond      0
30       Foundation      0
31        Bsmt Qual     80
32        Bsmt Cond     80
33    Bsmt Exposure     83
34   BsmtFin Type 1     80
35     BsmtFin SF 1      1
36   BsmtFin Type 2     81
37     BsmtFin SF 2      1
38      Bsmt Unf SF      1
39    Total Bsmt SF      1
40          Heating      0
41       Heating QC      0
42      Central Air      0
43       Electrical      1
44       1st Flr SF      0
45       2nd Flr SF      0
46  Low Qual Fin SF      0
47      Gr Liv Area      0
48   Bsmt Full Bath      2
49   Bsmt Half Bath      2
50        Full Bath      0
51        Half Bath      0
52    Bedroom AbvGr      0
53    Kitchen AbvGr      0
54     Kitchen Qual      0
55    TotRms AbvGrd      0
56       Functional      0
57       Fireplaces      0
58     Fireplace Qu   1422
59      Garage Type    157
60    Garage Yr Blt    159
61    Garage Finish    159
62      Garage Cars      1
63      Garage Area      1
64      Garage Qual    159
65      Garage Cond    159
66      Paved Drive      0
67     Wood Deck SF      0
68    Open Porch SF      0
69   Enclosed Porch      0
70       3Ssn Porch      0
71     Screen Porch      0
72        Pool Area      0
73          Pool QC   2917
74            Fence   2358
75     Misc Feature   2824
76         Misc Val      0
77          Mo Sold      0
78          Yr Sold      0
79        Sale Type      0
80   Sale Condition      0
81        SalePrice      0

In [16]:
for i in a[a['nulls']>500]['columns'].values:
    data.drop(i,axis=1,inplace=True,errors='ignore')

In [14]:
data.isna().sum()

Order                0
PID                  0
MS SubClass          0
MS Zoning            0
Lot Frontage       490
Lot Area             0
Street               0
Lot Shape            0
Land Contour         0
Utilities            0
Lot Config           0
Land Slope           0
Neighborhood         0
Condition 1          0
Condition 2          0
Bldg Type            0
House Style          0
Overall Qual         0
Overall Cond         0
Year Built           0
Year Remod/Add       0
Roof Style           0
Roof Matl            0
Exterior 1st         0
Exterior 2nd         0
Mas Vnr Area        23
Exter Qual           0
Exter Cond           0
Foundation           0
Bsmt Qual           80
Bsmt Cond           80
Bsmt Exposure       83
BsmtFin Type 1      80
BsmtFin SF 1         1
BsmtFin Type 2      81
BsmtFin SF 2         1
Bsmt Unf SF          1
Total Bsmt SF        1
Heating              0
Heating QC           0
Central Air          0
Electrical           1
1st Flr SF           0
2nd Flr SF           0
Low Qual Fin SF      0
Gr Liv Area          0
Bsmt Full Bath       2
Bsmt Half Bath       2
Full Bath            0
Half Bath            0
Bedroom AbvGr        0
Kitchen AbvGr        0
Kitchen Qual         0
TotRms AbvGrd        0
Functional           0
Fireplaces           0
Garage Type        157
Garage Yr Blt      159
Garage Finish      159
Garage Cars          1
Garage Area          1
Garage Qual        159
Garage Cond        159
Paved Drive          0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
Sale Type            0
Sale Condition       0
SalePrice            0
dtype: int64

In [17]:
data.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Area', 'Exter Qual', 'Exter Cond',
       'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Garage Type',
       'Garage Yr Blt', 'Garage Finish', 'Garage Cars', 'Garage Area',
       'Garage Qual', 'Garage Cond', 'Paved Drive', 'Wood Deck SF',
       'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch',
       'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [18]:
data['Price_Cat'] = pd.qcut(data['SalePrice'],q=3,labels=['low','medium','high'])

In [19]:
data

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice,Price_Cat
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,0,0,5,2010,WD,Normal,215000,high
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,0,120,0,0,6,2010,WD,Normal,105000,low
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,0,12500,6,2010,WD,Normal,172000,medium
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,0,0,0,0,4,2010,WD,Normal,244000,high
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,0,0,0,0,3,2010,WD,Normal,189900,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,0,0,0,0,3,2006,WD,Normal,142500,medium
2926,2927,923276100,20,RL,NaN,8885,Pave,IR1,Low,AllPub,...,0,0,0,0,6,2006,WD,Normal,131000,low
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,0,0,0,700,7,2006,WD,Normal,132000,low
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,0,0,0,0,4,2006,WD,Normal,170000,medium
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,0,0,0,0,11,2006,WD,Normal,188000,medium

In [20]:
data.columns

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Area', 'Exter Qual', 'Exter Cond',
       'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Garage Type',
       'Garage Yr Blt', 'Garage Finish', 'Garage Cars', 'Garage Area',
       'Garage Qual', 'Garage Cond', 'Paved Drive', 'Wood Deck SF',
       'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch',
       'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice', 'Price_Cat'],
      dtype='object')

In [21]:
X = data.drop(columns=['Order','PID','SalePrice','Price_Cat'])
y_reg = data['SalePrice']
y_cls = data['Price_Cat']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train_reg,X_test_reg,y_train_reg,y_test_reg = train_test_split(X,y_reg,test_size=0.2)

In [24]:
X_train_cls,X_test_cls,y_train_cls,y_test_cls = train_test_split(X,y_cls,test_size=0.2)

In [25]:
X_train_cls.shape

(2344, 73)

In [27]:
X_train_reg.shape

(2344, 73)

In [28]:
y_train_cls.replace({'low':0,'medium':1,'high':2},inplace=True)
y_test_cls.replace({'low':0,'medium':1,'high':2},inplace=True)

In [30]:
y_test_cls

103     1
690     0
1665    1
1671    0
1340    0
       ..
2427    2
2877    0
1423    1
2315    1
855     1
Name: Price_Cat, Length: 586, dtype: category
Categories (3, int64): [0 < 1 < 2]

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,GradientBoostingClassifier,GradientBoostingRegressor
from xgboost import XGBClassifier,XGBRegressor
from sklearn.metrics import accuracy_score,mean_squared_error,r2_score
from sklearn.compose import ColumnTransformer

In [41]:
num = X.select_dtypes(include=['int64','float64']).columns
cat = X.select_dtypes(include=['object']).columns

In [42]:
cat

Index(['MS Zoning', 'Street', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
       'Exterior 1st', 'Exterior 2nd', 'Exter Qual', 'Exter Cond',
       'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC',
       'Central Air', 'Electrical', 'Kitchen Qual', 'Functional',
       'Garage Type', 'Garage Finish', 'Garage Qual', 'Garage Cond',
       'Paved Drive', 'Sale Type', 'Sale Condition'],
      dtype='object')

In [45]:
num_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])
cat_pipe = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])
prep_pipe = ColumnTransformer(transformers=[
    ('num',num_pipe,num),
    ('cat',cat_pipe,cat) 
])
reg = {
    'Adaboost':AdaBoostRegressor(random_state=42),
    'GradientBoosting':GradientBoostingRegressor(random_state=42),
    'XGBoost':XGBRegressor(random_state=42)
}
cls = {
    'Adaboost':AdaBoostClassifier(),
    'GradientBoosting':GradientBoostingClassifier(),
    'XGBoost':XGBClassifier()
}

In [47]:
import numpy as np

In [48]:
for name,model in reg.items():
    print('======================================')
    pipe = Pipeline(steps=[
        ('preprocess',prep_pipe),
        ('model',model)
    ])
    pipe.fit(X_train_reg,y_train_reg)
    print('Fitting for',name,'Regressor')
    y_pred = pipe.predict(X_test_reg)
    rmse = np.sqrt(mean_squared_error(y_test_reg,y_pred))
    r2 = r2_score(y_test_reg,y_pred)
    print(f'{name}_rmse = {rmse}')
    print(f'{name}_r2 = {r2}')
    print('____________________________________\n\n')

======================================
Fitting for Adaboost Regressor
Adaboost_rmse = 33366.64691493275
Adaboost_r2 = 0.7967461540580087
____________________________________


======================================
Fitting for GradientBoosting Regressor
GradientBoosting_rmse = 20295.964928881305
GradientBoosting_r2 = 0.9247973666936469
____________________________________


======================================
Fitting for XGBoost Regressor
XGBoost_rmse = 24429.27817189857
XGBoost_r2 = 0.8910480737686157
____________________________________

In [49]:
for name,model in cls.items():
    print('======================================')
    pipe = Pipeline(steps=[
        ('preprocess',prep_pipe),
        ('model',model)
    ])
    pipe.fit(X_train_cls,y_train_cls)
    print('Fitting for',name,'Classifier')
    y_pred = pipe.predict(X_test_cls)
    rmse = np.sqrt(mean_squared_error(y_test_reg,y_pred))
    acc = accuracy_score(y_test_cls,y_pred)
    print(f'{name}_accuracy = {acc}')
    print('____________________________________\n\n')

======================================
Fitting for Adaboost Classifier
Adaboost_accuracy = 0.7935153583617748
____________________________________


======================================
Fitting for GradientBoosting Classifier
GradientBoosting_accuracy = 0.841296928327645
____________________________________


======================================
Fitting for XGBoost Classifier
XGBoost_accuracy = 0.8430034129692833
____________________________________